# Created by Jekyll Writer
title: Yunsong Zhong's Blog
author: Yunsong Zhong
description: Yunsong Zhong's Personal Blog
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: jekyllwriter
github_username: yszhong
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: ''
